# Generated by Django 4.0.4 on 2022-08-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_cliente_bairro_alter_cliente_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_do_Produto', models.CharField(max_length=100)),
            ],
        ),
    ]
