# Generated by Django 4.0.4 on 2022-08-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_produtos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
