# Generated by Django 4.0.4 on 2022-08-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_rename_produtos_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_de_Endereço', models.CharField(choices=[('Faturamento', 'Pessoa Jurídica'), ('Entrega', 'Pessoa Física')], max_length=20)),
                ('Logradouro', models.CharField(max_length=20)),
                ('Numero', models.CharField(max_length=6)),
                ('Complemento', models.CharField(max_length=20)),
                ('Prazo_pg', models.CharField(max_length=20)),
                ('Bairro', models.CharField(max_length=20)),
                ('Pais', models.CharField(default='Brasil', max_length=20)),
                ('UF', models.CharField(max_length=20)),
                ('Cidade', models.CharField(max_length=20)),
                ('Codigo', models.CharField(max_length=20)),
                ('CEP', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Codigo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Complemento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Endereco_Cobranca',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Endereco_Entrega',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Endereco_faturamento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Pais',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Prazo_pg',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='UF',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Cadastrar_Endereço',
            field=models.ManyToManyField(help_text='Novo Endereço', to='cadastro.endereco'),
        ),
    ]
