# Generated by Django 4.0.4 on 2022-08-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_endereco_remove_cliente_bairro_remove_cliente_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='Prazo_pg',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='Tipo_de_Endereço',
            field=models.CharField(choices=[('Faturamento', 'Endereço de Faturamento'), ('Entrega', 'Endereço de Entrega')], max_length=20),
        ),
    ]
