# Generated by Django 4.0.4 on 2022-08-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_remove_endereco_prazo_pg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Cadastrar_Endereço',
            field=models.ManyToManyField(help_text='Novo Endereço', max_length=200, to='cadastro.endereco'),
        ),
    ]
