# Generated by Django 4.0.4 on 2022-08-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_alter_cliente_cadastrar_endereço'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Cadastrar_Endereço',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Cadastrar_Endereço',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.endereco'),
        ),
    ]
