# Generated by Django 4.0.4 on 2022-08-09 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_remove_cliente_cadastrar_endereço_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Cadastrar_Endereço',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.endereco'),
        ),
    ]
