# Generated by Django 4.0.4 on 2022-08-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_alter_cliente_cadastrar_endereço'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Cadastrar_Endereço',
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='cadastro.endereco'),
            preserve_default=False,
        ),
    ]
