# Generated by Django 4.0.4 on 2022-08-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_alter_endereco_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='cadastro.endereco'),
        ),
    ]
