# Generated by Django 4.0.4 on 2022-08-09 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_alter_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='Responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='cadastro.cliente'),
            preserve_default=False,
        ),
    ]
