# Generated by Django 4.0.4 on 2022-08-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_emails_fornecedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails',
            new_name='Email',
        ),
    ]
