# Generated by Django 4.0.4 on 2022-08-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_rename_emails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to='cadastro.fornecedor'),
        ),
    ]
