# Generated by Django 4.0.4 on 2022-08-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0024_alter_email_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='Responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='cadastro.cliente'),
        ),
    ]
