# Generated by Django 4.0.4 on 2022-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_alter_email_fornecedor_alter_endereco_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Certificado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Cest',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Csit_Tributaria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Data_Atualizacao',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Data_Cadatro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Numero_Certificado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Numero_Serie',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Patrimonio_NCM',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Pedidos',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Pendência',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Preco_uni',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Uni_medida',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='Validade',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
