# Generated by Django 4.0.4 on 2022-08-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0027_produto_certificado_produto_cest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='Observacoes',
            field=models.CharField(max_length=200),
        ),
    ]
